my_module.settings:
  type: config_object
  label: 'My module basic settings'
  mapping:
    title:
      label: 'Title'
      type: label
    select:
      label: 'Select'
      type: string
    checkbox:
      label: 'Checkbox'
      type: boolean
    checkboxes:
      label: 'Checkboxe'
      type: sequence
    radios:
      label: 'Radios'
      type: string
    message:
      label: 'Message'
      type: text
    ckeditor:
      label: 'Ckeditor'
      type: text_format
    language:
      type: string
      label: 'Language code'
